:queues:
  - default

:schedule:
  annual_gift_removal_worker:
    cron: "0 0 1 1 *" # At 00:00 on day-of-month 1 in January
    class: AnnualGiftRemovalWorker
  work_reminder_worker:
    cron: "30 6 * * 1-5" # At 06:30 on every day-of-week from Monday through Friday
    class: WorkReminderWorker
